# Generated by Django 2.1.3 on 2018-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181204_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
