# Generated by Django 2.1.3 on 2018-12-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181204_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='picture',
            field=models.ImageField(blank=True, upload_to='home/static/images'),
        ),
    ]
